discordjs/discord.js-modules

.github/workflows/test-cron.yml, .github/workflows/test.yml
This uses the GitHub Actions cache step to cache dependencies for npm between workflow executions. This will make workflow executions significantly faster, since dependencies can be reused rather than reinstalled.
**Status**
=> ci: cache npm

package-lock.json, packages/voice/README.md, packages/voice/package.json, packages/voice/tsconfig.json
This pull request initialises the voice package for Discord.js.
**Status**
=> chore: initialise voice package

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SUPPORT.md
Typings are no longer required in this repo, so this PR removes it from the pull request template.
This PR also cleans up some associated files.
**Status**
=> chore: cleanup PR template, support and contributing files

.github/CODE_OF_CONDUCT.md, .github/COMMIT_CONVENTION.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> docs: manual prettier over markdown files

lerna.json, package.json, packages/collection/package.json, packages/core/package.json, packages/discord.js/package.json, packages/rest/package.json, packages/types/package.json, packages/voice/package.json, packages/ws/package.json
=> chore: json schema for all necessary files

package-lock.json, package.json
=> chore: tests

.github/workflows/lint-cron.yml, .github/workflows/lint.yml, .github/workflows/test-cron.yml, .github/workflows/test.yml, README.md
=> chore: rename tests

.github/CONTRIBUTING.md, .github/workflows/test-cron.yml, .github/workflows/test.yml, .gitignore, lerna.json, package.json, packages/core/__tests__/index.test.ts, packages/core/src/index.ts
=> test: coverage

.github/workflows/test.yml, README.md, package.json
=> test: upload coverage

packages/collection/package.json, packages/core/package.json, packages/discord.js/package.json, packages/rest/package.json, packages/types/package.json, packages/voice/package.json, packages/ws/package.json
Does not need a lot of explaining but it is needed for syntax features like:
`export * as x from 'y';`
**Status**
=> chore(pkg): install tslib on all packages

packages/collection/tsconfig.json, packages/core/tsconfig.json, packages/discord.js/tsconfig.json, packages/rest/tsconfig.json, packages/types/tsconfig.json, packages/voice/tsconfig.json, packages/ws/tsconfig.json, tsconfig.json
=> chore(tsconfig): hoist generic compiler options

.gitignore, package-lock.json, package.json
=> docs: init typedoc

packages/collection/__tests__/collection.test.ts, packages/collection/src/Collection.ts, packages/collection/src/index.ts
=> feat(collection): collection package

babel.config.js, jest.config.js, lerna.json, package-lock.json, package.json, packages/collection/__tests__/collection.test.ts, packages/collection/package-lock.json, packages/collection/package.json, packages/collection/src/Collection.ts, packages/collection/tsconfig.json, packages/core/package-lock.json, packages/core/package.json, packages/core/tsconfig.json, packages/discord.js/package-lock.json, packages/discord.js/package.json, packages/discord.js/tsconfig.json, packages/rest/package-lock.json, packages/rest/package.json, packages/rest/tsconfig.json, packages/types/package-lock.json, packages/types/package.json, packages/types/tsconfig.json, packages/voice/package-lock.json, packages/voice/package.json, packages/voice/tsconfig.json, packages/ws/package-lock.json, packages/ws/package.json, packages/ws/tsconfig.json, tsconfig.base.json, tsconfig.eslint.json
=> refactor(*): use babel-jest instead of ts-jest

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SUPPORT.md
Applying https://github.com/discordjs/discord.js/pull/5269 to -next, removing the clutter before it even starts.
If you have feedback please post it in the linked PR (i will apply it back to this PR) unless it has to do with specific adaptations that need to be made here, because an approach has fundamentally changed.
=> chore(*): streamline issue and PR templates and redirects

packages/rest/src/lib/REST.ts
This PR creates typings for REST events.
=> types(REST): event listener typings

packages/rest/src/lib/CDN.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/handlers/IHandler.ts, packages/rest/src/lib/handlers/SequentialHandler.ts
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
=> refactor(Rest): `xID` to `xId`

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, README.md, package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/rest/CHANGELOG.md, packages/rest/package.json, packages/ws/CHANGELOG.md, packages/ws/package.json
Updates the branch name from master => main, and the repo name from -next to -modules
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> chore: update repo/branch name

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/SUPPORT.md
This uses the vanity URL of the discord.js server, allowing links to be more shorter and easily remembered. 
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> chore: update Discord.js server invite

packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
=> feat(CDN#guildIcon): implement dynamic logic

packages/rest/__tests__/RequestHandler.test.ts, packages/rest/src/index.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/errors/RateLimitError.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/utils/constants.ts
Ported from https://github.com/discordjs/discord.js/pull/5659
~~Needs #51~~
- This PR changes the library's interface (methods or parameters added)
=> feat(RateLimits): optionally error on ratelimits

packages/rest/src/lib/CDN.ts
Fixes some oopsies from #84
- I know how to update typings and have done so
=> fix(CDN): use correct types

packages/rest/__tests__/REST.test.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/utils/constants.ts
Ported from https://github.com/discordjs/discord.js/pull/6739
~~Needs #77~~
- This PR changes the library's interface (methods or parameters added)
=> feat(Rest): add response and request events

packages/rest/package.json, yarn.lock
Thankfully, no code changes were needed, but bumping just in case.
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> chore(Deps): update `@sapphire/snowflake` to `^3.0.0`

packages/rest/__tests__/DiscordAPIError.test.ts, packages/rest/__tests__/REST.test.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/errors/DiscordAPIError.ts, packages/rest/src/lib/handlers/SequentialHandler.ts
Closes: #90
Alternative to #92 with theoretically significantly better performance on every request and support for the very different error format from oauth
- This PR changes the library's interface (methods or parameters added)
=> feat(Rest): add support for oauth2 endpoints
